name: 'Prometheus Prow Bot'
description: 'Chat-ops automation for Prometheus repositories'
author: 'Prometheus Team'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'message-circle'
  color: 'orange'
